import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import logo from '../public/logo.png'
import hero from '../public/hero.png'
import circle from '../public/circle.png'
import cable from '../public/cable1.jpg'
import charger from '../public/charger2.jpg'
import earphone from '../public/earphone3.jpg'
import holder from '../public/holder4.jpg'
import lifestyle from '../public/lifestyle5.jpg'
import seris from '../public/series6.jpg'
import power from '../public/power7.jpg'
import bundle from '../public/bundle8.jpg'
import apple from '../public/aswa.svg'
import numi from '../public/numiteg.svg'
import bekami from '../public/bekami.svg'
import blueher from '../public/blueheron.svg'
import briza from '../public/briza.svg'
import steppay from '../public/steppay.svg'
import jogjapay from '../public/jogjapay.svg'
import tes from '../public/tes.jpg'
import tes2 from '../public/tes2.jpg'
import {AiFillShopping , AiFillInstagram,} from 'react-icons/ai'
import {FaTiktok} from 'react-icons/fa'
import Navbaru from '../components/Navbar.js'
export default function Home() {
  return (
    <>
       <Head>
        <title>Rexi Landingpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {/* header */}
       <Navbaru/>
        {/* header end */}
        <section id='home' className=' bg-primary pt-32 pb-16'>
            <div className='container'>
                <div className='flex flex-wrap px-4'>
                    
                    <div className='w-full lg:w-1/2 px-4 mx-auto mb-10 self-center'>
                      <Image src={logo} alt="" className='w-[200px] lg:w-[250px]'/>
                      <h1 className='font-lato text-xl lg:text-2xl text-dark1 my-2'>Smartphone Accesories</h1>
                      <p className='text-sm lg:text-lg text-dark2 max-w-md'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit, aspernatur.</p>
                    </div>

                    <div className='w-full lg:w-1/2 px-4 mb-10 relative'>
                      
                        <Image src={circle} alt="" className='mx-auto ' />
                        <Image src={hero} alt="" className=' absolute  bottom-0 translate-x-1/2 -left-1/2 lg:translate-x-0 lg:left-0 lg:mx-auto'/>
                      
                    </div>
                </div>
            </div>
        </section>
        <section id='about' className=' bg-secondary px-4'>
          <div className='container bg-white rounded-t-[70px]'>
            <div className='text-center py-4'>
                <h1 className='text-2xl font-bold mt-10 font-lato text-primary'>Tentang Kami</h1>
            </div>
            <div className='flex flex-wrap'>
              <div className='w-full lg:w-1/2 px-4 py-2 mb-5 '>
                  <p className='text-sm text-dark2 font-lato mx-auto my-2 text-justify max-w-md'>Di awal tahun 2018, kami melihat potensi 
                          pasar aksesoris smartphone saat berada 
                          di brand martphone. Kami percaya bawha 
                          potensi pasar yang sangat besar dan juga 
                          peluang untuk engembangkan merek
                          baru untuk menjadi pemimpin pasar baru.</p>
                  <p className='text-sm text-dark2 font-lato mx-auto my-2 text-justify max-w-md'>
                  Dengan pengalaman kami dalam 
                  pengembangan bisnis di pasar aksesoris HP
                    dan kepercayaan kami pada konsep bisnis 
                  'saling menguntungkan' dimana semua 
                  orang menang , muncullah REXI.
                  </p>
              </div>
              <div className='w-full lg:w-1/2 px-4 py-2 mb-5'>
                  <p className='text-sm text-dark2 mx-auto font-lato my-2 text-justify max-w-md'>
                  Perusahaan REXI selalu berkomitmen untuk 
                  menciptakan produk dan layanan terbaik , mengimplementasikan teknologi ke dalam 
                  kehidupan sehari-hari konsumen, melalui
                  inovasi dan riset yang dilakukan secara terus 
                  menerus, kami menyediakan produk yang pastinya sangat berbeda di pasaran dan 
                  memiliki aya saing yang kuat untuk para konsumen.
                    </p>
                  <p className='text-sm text-dark2 mx-auto font-lato my-2 text-justify max-w-md'>
                  Dengan usaha dan kerja keras kami, REXI pasti 
 akan dapat bertahan dan berkembang dengan pesat!
                  </p>
              </div>
            </div>
          </div>
        </section>
        {/* section product */}
        <section id='product' className='pt-32 pb-32 bg-white'>
          <div className='container'>
            <div className='w-full max-w-md mx-auto py-8'>
                <h1 className='font-lato font-bold text-3xl text-center mb-5'>Product Kami</h1>
                <p className='text-sm text-dark2 font-lato '>Temukan accesories smartphone terbaikmu  pada product-product REXI</p>
            </div>
            <div className='flex flex-wrap px-4'>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={cable} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={charger} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={earphone} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={holder} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={lifestyle} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={seris} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={power} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
              <div className='w-full lg:w-1/4 md:w-1/2 px-4 mb-5'>
                  <div className='rounded-2xl shadow-lg  w-72 h-80 mx-auto overflow-hidden'>
                      <Image src={bundle} alt="cable data" className='-translate-y-14'/>
                      <p className='px-4 -translate-y-14'>cek cable data sesuai kebutuhanmu</p>
                      <a href=""><button className='-translate-y-10 bg-primary px-4 py-2 ml-4 rounded-lg shadow-lg font-lato font-bold hover:bg-secondary'>Cek Items</button></a>
                  </div>
              </div>
            </div>
          </div>
        </section>
        {/* suportby */}
        <section id='support' className='pt-32 pb-16 bg-gray-200'>
          <div className='container'>
            <div className='mx-w-md mx-auto w-full px-4'>
                <h1 className='font-bold text-2xl lg:text-3xl text-center text-primary font-lato'>Support By</h1>
                <p className='text-sm lg:text-lg font-semibold font-lato text-dark1 text-center my-4'>Produk-produk rexi di support oleh</p>
               <div className='flex flex-wrap justify-center px-4 items-center'>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={apple} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={numi} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={briza} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={bekami} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={blueher} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={jogjapay} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
                  <div className='w-full  lg:w-1/4 md:w-1/3'>
                      <Image src={steppay} alt="" className='mx-auto scale-50 grayscale opacity-20 hover:grayscale-0 hover:opacity-100'/>
                  </div>
               </div>
            </div>
          </div>
        </section>
        <section id='post' className='pt-32 pb-32 bg-dark2'>
          <div className='container'>
              <div className='flex flex-wrap justify-center items-center px-4'>
                  <div className='w-full lg:w-1/2 px-4 mb-5'>
                      <div className='rounded-xl shadow-xl overflow-hidden bg-slate-200 w-80 lg:w-96 h-96 mx-auto'>
                        <Image src={tes} alt="" className='-translate-y-1/4 lg:-translate-y-1/3'/>
                        <p className='-translate-y-16 px-4 mb-4 lg:-translate-y-32'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, deserunt?</p>
                      <a href=""><div className='px-2 py-2 mx-4 -translate-y-16 lg:-translate-y-32 bg-primary text-center rounded-lg font-bold text-lg font-lato hover:bg-secondary'>selanjutnya</div></a>
                      </div>
                  </div>

                  <div className='w-full lg:w-1/2 px-4 mb-5'>
                      <div className='rounded-xl shadow-xl overflow-hidden bg-slate-200 w-80 lg:w-96 h-96 mx-auto'>
                        <Image src={tes2} alt="" className='-translate-y-1/4 lg:-translate-y-1/3'/>
                        <p className='-translate-y-16 lg:-translate-y-32 px-4 mb-4'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, deserunt?</p>
                       <a href=""><div className='px-2 py-2 mx-4 -translate-y-16 lg:-translate-y-32 bg-primary text-center rounded-lg font-bold text-lg font-lato hover:bg-secondary'>selanjutnya</div></a>
                      </div>
                  </div>
              </div>
          </div>
        </section>
        <section className='pt-32 pb-16 bg-primary'>
            <div className='container'>
                <div className='flex flex-wrap '>
                    <div className='w-full lg:w-1/3 px-4  mb-5'>
                    <Image src={logo} alt="" className='w-[100px] lg:w-[150px]'/>
                      <h1 className='font-lato font-semibold text-sm lg:text-base text-dark1 my-2'>Smartphone Accesories</h1>
                      <p>Jl.cantel no 15 , umbul harjo</p>
                      <p>Yogyakarta</p>
                    </div>
                    <div className='w-full lg:w-1/3 px-4 mb-5 '>
                      <h1 className='text-xl font-bold font-lato mb-5'>Direct Link</h1>
                      <a href="" className='my-2 text-dark1 hover:text-white'><h1>Home</h1></a>
                      <a href="" className='my-2 text-dark1 hover:text-white'><h1>About</h1></a>
                      <a href="" className='my-2 text-dark1 hover:text-white'><h1>Product</h1></a>
                      <a href="" className='my-2 text-dark1 hover:text-white'><h1>Support</h1></a>
                      <a href="" className='my-2 text-dark1 hover:text-white'><h1>post</h1></a>
                    </div>
                    <div className='w-full lg:w-1/3 px-4 mb-5'>
                      <h1 className='lg:text-center font-lato font-bold text-xl mb-8'>Media Sosial</h1>
                      <div className='flex flex-warp justify-center text-7xl '>
                            <div className='w-full lg:w-1/3 flex justify-center'>
                                <AiFillInstagram/>
                            </div>
                            <div className='w-full lg:w-1/3 flex justify-center'>
                                <div className=''><AiFillShopping/></div>
                            </div>
                            <div className='w-full lg:w-1/3 flex justify-center'>
                                <FaTiktok/>
                            </div>
                      </div>
                    </div>
                </div>
            </div>
        </section>
    
      </main>
      
    </>
  )
}
